# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fc57c01eafb35417e3c930cacf172e5067d956d70ad5a38418c0d8e78ba7038f288dabd18586dd17103dc8ac87615e6cdf6e5443e5aff15a74e0d491720571d

test:
  secret_key_base: f83d8593f82c32067e54497a876d9f792e9faf0f159d9ec83ba09a43e69f772c014fbed832b3aa8d8b1fb436af1d9516042ade4d31785fb1e2641aea99750826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
